#!/bin/sh
set -e
# List friends

online() {
    if [ $1 -eq 1 ]; then
        echo "Online"
    else
        echo "Offline"
    fi
}

# Try to determine whether this is run from within
# a ratox directory and complain if not.
check_if_dir(){
    # "grouping hack" to prevent output to stdout on FreeBSD
    if ! { lsof id |grep -q '^ratox';} > /dev/null 2>&1 || [ ! -r id ]; then
        echo "ERROR: Is this a ratox directory?" >&2
        exit 1
    fi
}

print_output() {
    IDS=$(ls |grep '[A-Z0-9]\{64\}')
    for ID in $IDS; do
        NAME=$(cat $ID/name | tr -d '\n')
        STATUS=$(cat $ID/status | cut -c-30 |tr -d '\n')
        STATE=$(cat $ID/state | sed 's/.*/\u&/')
        ONLINE=$(cat $ID/online)
        if [ $STATE != 'None' ] && [ "$ONLINE" -ne 0 ]; then
            ONLINE=$STATE
        else
            ONLINE=$(online $ONLINE)
        fi
        printf "%-12s\t%-8s\t%-30s\t\t%-30s\n" $(echo $ID | cut -c-12) "$ONLINE" "$NAME" "$STATUS"
    done
}


check_if_dir
print_output
