#!/bin/sh
# List friends

set -e
green() { printf "\033[1;32m$1\033[0;39;49m\n"; }
red() { printf "\033[1;31m$1\033[0;39;49m\n"; }
yellow() { printf "\033[1;33m$1\033[0;39;49m\n"; }

set_state() {
    if [ "$1" = 'none' ]; then
        green "*"
    elif [ "$1" = 'away' ]; then
        yellow "*"
    else
        red "*"
    fi
}

# Try to determine whether this is run from within
# a ratox directory and complain if not.
check_if_dir(){
    # "grouping hack" to prevent output to stdout on FreeBSD
    if ! { fstat id |grep -q 'ratox';} > /dev/null 2>&1 || [ ! -r id ]; then
        echo "ERROR: Is this a ratox directory?" >&2
        exit 1
    fi
}

print_output() {
    IDS=$(ls |grep '[A-Z0-9]\{64\}')
    for ID in $IDS; do
        NAME=$(cat $ID/name | tr -d '\n' | cut -c-32)
        STATUS=$(cat $ID/status | cut -c-40 |tr -d '\n')
        STATE=$(cat $ID/state)
        ONLINE=$(cat $ID/online)
        if [ "$ONLINE" -ne 0 ]; then
        ONLINE="$(set_state $STATE)"
        else
            ONLINE='o'
        fi
        printf "%-8s | %s | %-32s\t\t%-40s\n" $(echo $ID | cut -c-8) "$ONLINE" "$NAME" "$STATUS"
    done
}


check_if_dir
print_output
